steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:${COMMIT_SHA}'
      - '.'

  # Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:${COMMIT_SHA}'

  # SSH into the instance and update Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        gcloud compute ssh my-instance --zone us-central1-a --command="docker pull us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:${COMMIT_SHA} && docker stop my-container && docker rm my-container && docker run -d --name my-container us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:${COMMIT_SHA}"
      
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

images:
  - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:latest'
