steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/analog-context-413503/kevinleander/flaskapp:${COMMIT_SHA}', '.']
  # Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/analog-context-413503/kevinleander/flaskapp:${COMMIT_SHA}']

  # Update the compute instance with the new Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'update-container', 'my-instance', '--container-image', 'us-central1-docker.pkg.dev/analog-context-413503/kevinleander/flaskapp:${COMMIT_SHA}']

options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  defaultLogsBucket: 'gs://your-build-logs-bucket' # Replace with your build logs bucket
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

images:
  # Store images in Google Artifact Registry
  - us-central1-docker.pkg.dev/analog-context-413503/kevinleander/flaskapp:${COMMIT_SHA}