steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:latest'
      - '.'

  # Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:latest'

  # Reset the specified instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'instances', 'reset', 'my-instance', '--zone', 'us-central1-a']
options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET test
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

images:
  # Store images in Google Artifact Registry
  - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:latest'
