steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:${COMMIT_SHA}'
      - '.'

  # Step 2: Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:${COMMIT_SHA}'

  # Step 3: Update the compute instance with the new Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'compute'
      - 'instances'
      - 'update-container'
      - 'my-instance'
      - '--container-image'
      - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:${COMMIT_SHA}'
      - '--zone'
      - 'us-central1-a'
 
options:
  # Set defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

images:
  # Store images in Google Artifact Registry
  - 'us-central1-docker.pkg.dev/analog-context-413503/finaltry/flaskapp:latest'  # Update the repository and tag
